### PR TITLE
Add `clash save` command

### PR DESCRIPTION
**Pull request by daxida**
Probably just the bases for fixing #20 in the future. I don't think I'll be able to manage the browsing or other features discussed there.

### CODE REVIEW

**Review by Andriamanitra — COMMENTED** [review]
This feature needs to do more than just move files to warrant its existence – for example store the solutions in a format that the tool can execute[^1]. I don't really want to add any features that are inferior to a one-line shell script that does the same thing. I think it would be a good idea to outline the use cases for this command and think about how we want it to work before we start implementing it.

[^1]: it should include at least the build command, the run command and the source file(s) – a sqlite3 database might be a good fit to store all the metadata?

**Comment by daxida** [comment]
I have no experience with sqlite3 so I can't comment on that. If we end up going that direction maybe you can give me some pointers.

For the build command, I don't see how to include it other than either manually adding it to the `save` command (some flag), or fetching it from a configuration file that would have been set up previously for `clash run`.

The way I see using this myself would be mainly to store valid solutions (so personally I find no need for a build command, I will probably very rarely run those again). That only requires moving them and eventually adding a renaming option to the command.

**Comment by Andriamanitra** [comment]
> The way I see using this myself would be mainly to store valid solutions (so personally I find no need for a build command, I will probably very rarely run those again). That only requires moving them and eventually adding a renaming option to the command.

IMO just saving a solution file is a task for a shell script rather than `clash`. A shell script that uses `mv` is easier to change (no compilation step) and more flexible (you can easily make the filename and location be whatever). Maybe this use case would be better served by a command that prints the handle of the current clash so you could use it like this?

```sh
mv $FILENAME ~/my/clash/solution/directory/$(date +"%Y-%m-%d-%H%M")_$(clash showhandle)_$FILENAME
```

**Comment by daxida** [comment]
I do not think this PR is going anywhere, should we close it?

**Pull request closed without merging**
